services:
  app:
    container_name: grpc-go
    ports:
      - "50051:50051"
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    working_dir: /root/go/src
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - .:/root/go/src
    networks:
      - local_network
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  local_network:
    driver: bridge

volumes:
  mongo_data:
